url = "https://www.bjornvandijkman.com"
languageCode = "en-us"
title = "Björn van Dijkman's Blog"
theme = "m10c"

[params]
  author = "Björn van Dijkman"
  description = "A data engineering blog"


  [[params.social]]
    icon = "github"
    name = "GitHub"
    url = "https://github.com/bjornvandijkman1993"

  [[params.social]]
    icon = "linkedin"
    name = "Linkedin"
    url = "https://www.linkedin.com/in/björn-van-dijkman-5103a671/"
