baseURL: "https://www.bjornvandijkman.com"
languageCode: "en-us"
title: "Björn van Dijkman's Blog"
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: en
defaultContentLanguageInSubdir: true

languages:
  en:
    languageName: "English"
    weight: 1
    menu:
      main:
        - name: About
          url: about/
          weight: 5
        - name: Blog
          url: posts/
          weight: 7
        - name: Archive
          url: archives/
          weight: 8
        - name: Tags
          url: tags/
          weight: 9
        - name: Search
          url: search/
          weight: 11

params:

  
  env: production
  keywords: [Blog, OpenSource, Coding, Golang, Programming]
  author: "Björn van Dijkman"
  defaultTheme: light
  disableThemeToggle: true
  # TocSide: 'left'

  ShowToc: true
  TocOpen: true
  ShowBreadCrumbs: false
  ShowReadingTime: true
  ShowPostNavLinks: true
  ShowShareButtons: true
  ShowCodeCopyButtons: true
  displayFullLangName: true

  homeInfoParams:
    Title: "Hi, I'm Björn van Dijkman 👋"
    Content: "**Data** and **Machine Learning Engineer** 🧑‍💻"
    imageUrl: "avatar.jpg"
    imageWidth: 120 # custom size
    imageHeight: 120 # custom size

  socialIcons:
    - name: github
      url: "https://github.com/bjornvandijkman1993"
    - name: linkedin
      url: "https://www.linkedin.com/in/björn-van-dijkman-5103a671/"
    - name: youtube
      url: "https://www.youtube.com/channel/UCw5ubOsLoMwoAhBwXq8ksZg"

taxonomies:
  category: categories
  tag: tags
  series: series


outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary